spring.application.name=syncly

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/syncly_db
spring.datasource.username=postgres
spring.datasource.password=syncly1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Slack Incoming Webhook
slack.webhook.url=https://hooks.slack.com/services/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



# Slack Bot Token (for individual DMs via conversations.open + chat.postMessage)
slack.bot.token=xoxb-8244807258401-8628001281335-Np09gqeQHNNTmuzmzjLHTsfe
                
                
# Logging
logging.level.root=INFO
logging.level.com.alice.syncly=INFO
logging.level.org.springframework.scheduling=DEBUG

