spring.profiles.include=secret
spring.application.name=syncly

# PostgreSQL DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/syncly_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:syncly1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Slack (로컬: application-secret.properties가 덮어씀 / Render: 환경변수로 주입)
slack.webhook.url=${SLACK_WEBHOOK_URL:}
slack.bot.token=${SLACK_BOT_TOKEN:}
slack.invite.url=${SLACK_INVITE_URL:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Gmail SMTP (로컬: application-secret.properties가 덮어씀 / Render: 환경변수로 주입)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

# 2. 보안 방식을 STARTTLS에서 SSL 활성화로 변경 (클라우드 차단 해제 핵심)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# 3. 네트워크 무한 대기로 인한 서버 다운 방지 (타임아웃 설정 추가)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000






# Logging
logging.level.root=INFO
logging.level.com.alice.syncly=INFO
logging.level.org.springframework.scheduling=DEBUG

