spring.application.name=syncly

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/syncly_db
spring.datasource.username=postgres
spring.datasource.password=syncly1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Slack Incoming Webhook
slack.webhook.url=YOUR_SLACK_WEBHOOK_URL