name: Keep Render Server Alive

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping request to Render
        run: |
          curl -I https://syncly-dtj3.onrender.com
